#!/bin/bash
OPTION=$(echo -e "youtube\ngoogle\nreddit\nfacebook\ncancel" | dmenu)
echo $OPTION

case $OPTION in 
	"youtube") chromium "www.youtube.com";;
	"google") chromium "www.google.com";;
	"reddit") chromium "www.reddit.com";;
	"facebook") chromium "www.facebook.com";;
	"cancel") ;;
	*) chromium "www.$OPTION.com";;
esac 

