#!/bin/bash 
# Shutdown script for dmenu, Jelle Meijer
option=$(echo -e "shutdown\nreboot\nsuspend\ncancel" | dmenu)

case $option in 
	"shutdown") shutdown now;;
	"reboot") shutdown -r now;;
	"suspend") systemctl suspend;;
	"cancel") shutdown -c;;
esac

